=== gvenkata1976/books/utilities/actiweb/src/main/java/config/navigation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/navigation" xmlns:tns="http://www.example.org/navigation" elementFormDefault="qualified">
<element name="organization">
	<complexType >
		<sequence>
			<element name="tabs">
				<complexType>
					<sequence>
					<element name="toolbar">
						<complexType >
							<sequence>
							<element name="actions">
									<complexType >
										<sequence>
										<element name="action" minOccurs="1" maxOccurs="8">
											<complexType >
												<attribute name="name" type="string"/>
												<attribute name="value" type="string"/> 
											</complexType>	
										</element>
										</sequence> 
									</complexType>
							</element>
							</sequence>
						</complexType>
					</element>
					
					<element name="tab" minOccurs="1" maxOccurs="50">
					<complexType >
						<attribute name="name" type="string"/>
						<attribute name="value" type="string"/>
						<attribute name="parent" type="string"/>
						<attribute name="default" type="boolean"/>
						<attribute name="toolbar" type="boolean"/> 
					</complexType>	
						<!--attributes name, value, parent, default, toolbar-->
					</element>

					
					
					</sequence>
				</complexType>			
			</element>
		</sequence>
	</complexType>
</element>
</schema>

=== gvenkata1976/books/utilities/actiweb/src/main/java/config/navigation.xml
<?xml version="1.0" encoding="UTF-8"?>
<organization xmlns="http://www.example.org/navigation" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/navigation navigation.xsd ">
  <tabs>
	<toolbar>
			<actions>
					<action name="add" value="Add" />
					<action name="refresh" value="Refresh" />
			</actions>
		</toolbar>
		<tab name="employee" value="Home" default="true" toolbar="false" />
		<tab name="employee" value="Search" />
		<tab name="employee" value="Employee" />
		<tab name="employee" value="Reports" />
		<tab name="employee" value="Tools" />
		 
		<tab name="user" value="User" parent="tools"/>
		<tab name="role" value="Role" parent="tools"/>
		<tab name="function" value="Function" parent="tools"/>
		<tab name="country" value="Country" parent="tools"/>
		<tab name="region" value="Region" parent="tools"/>
		<tab name="department" value="Department" parent="tools"/>
  </tabs>
</organization>
